services:
  - type: web
    name: inter-nmims-basketball-2025
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_MAPBOX_TOKEN
        sync: false # Set this in Render dashboard
    buildFilter:
      paths:
        - src/**/*
        - public/**/*
        - package.json
        - package-lock.json
    autoDeploy: false
